version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whiteboard-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://meharfatimak:oLn3C83JMDXZD9pf@cluster0.cacbl.mongodb.net/whiteboard?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_HOST=redis-14494.c226.eu-west-1-3.ec2.redns.redis-cloud.com
      - REDIS_PORT=14494
      - REDIS_PASSWORD=cRvjHgI972UVnGR7ls2ZFbppr93nJwB4
      - SERVER_PORT=5000
      - REDIS_SERVER_IP=redis
      - REDIS_SERVER_PORT=6379
    networks:
      - app-network

    depends_on:
      - redis

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
